CREATE TABLE users (
    id BIGSERIAL PRIMARY KEY,
    username VARCHAR(50) UNIQUE NOT NULL,
    email VARCHAR(100) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    role VARCHAR(20) DEFAULT 'USER',
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE streamers (
    id BIGSERIAL PRIMARY KEY,
    user_id BIGINT NOT NULL,
    display_name VARCHAR(100),
    donate_token VARCHAR(100) UNIQUE NOT NULL,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_user
        FOREIGN KEY(user_id)
        REFERENCES users(id)
        ON DELETE CASCADE
);


CREATE TABLE donations (
    id BIGSERIAL PRIMARY KEY,
    streamer_id BIGINT NOT NULL,
    donor_name VARCHAR(100),
    amount NUMERIC(10,2) NOT NULL,
    message TEXT,
    status VARCHAR(20) DEFAULT 'PENDING',
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_streamer
        FOREIGN KEY(streamer_id)
        REFERENCES streamers(id)
        ON DELETE CASCADE
);


CREATE TABLE payments (
    id BIGSERIAL PRIMARY KEY,
    donation_id BIGINT NOT NULL,
    provider VARCHAR(50),
    transaction_code VARCHAR(100),
    status VARCHAR(20),
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_donation
        FOREIGN KEY(donation_id)
        REFERENCES donations(id)
        ON DELETE CASCADE
);


CREATE TABLE streamer_settings (
    id BIGSERIAL PRIMARY KEY,
    streamer_id BIGINT NOT NULL,
    alert_sound VARCHAR(255),
    alert_image VARCHAR(255),
    min_amount NUMERIC(10,2) DEFAULT 0,

    CONSTRAINT fk_streamer_settings
        FOREIGN KEY(streamer_id)
        REFERENCES streamers(id)
        ON DELETE CASCADE
);

CREATE INDEX idx_donations_streamer_id 
ON donations(streamer_id);

CREATE INDEX idx_donations_created_at 
ON donations(created_at DESC);

CREATE INDEX idx_streamers_token 
ON streamers(donate_token);

CREATE TABLE IF NOT EXISTS public.product_promotions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    image_url TEXT NULL,
    url TEXT NULL,
    streamer_id BIGINT NULL,
    title TEXT NULL,
    CONSTRAINT product_promotions_pkey PRIMARY KEY (id),
    CONSTRAINT product_promotions_streamer_id_fkey
        FOREIGN KEY (streamer_id) REFERENCES streamers (id)
);

ALTER TABLE public.product_promotions
    ADD COLUMN IF NOT EXISTS image_url TEXT NULL;

CREATE TABLE IF NOT EXISTS public.streamer_blocks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    streamer_id BIGINT NOT NULL,
    user_id BIGINT NULL,
    CONSTRAINT streamer_blocks_pkey PRIMARY KEY (id),
    CONSTRAINT streamer_blocks_streamer_id_fkey
        FOREIGN KEY (streamer_id) REFERENCES streamers (id),
    CONSTRAINT streamer_blocks_user_id_fkey
        FOREIGN KEY (user_id) REFERENCES users (id)
);
