package org.example.donatebackend.exception;

public enum ErrorCode {
    STREAMER_ALREADY_EXISTS,
    TOKEN_ALREADY_EXISTS,
    USER_NOT_FOUND,
    INVALID_REQUEST,
    INTERNAL_ERROR,
    REPORT_NOT_FOUND,
    REPORT_DUPLICATE_PENDING,
    REPORT_BLOCKED,
    TARGET_NOT_FOUND,
    INVALID_REPORT_STATUS
}